
title: "viniskitchen"
description: "Homestyle Indian food and catering. Lady‑owned, community‑loved."
timezone: America/Los_Angeles
theme: minimal-mistakes-jekyll
plugins: [jekyll-include-cache]
markdown: kramdown

author: "Vineetha Pai"
email: "reachus@vinniskitchen.com"
baseurl: "" 
url: "https://devsite.vinniskitchen.com"
# add after existing options
sass:
  style: compressed