
image: <img class="header-logo" src="/assets/images/Banner_BG.png" alt="Vinni's Kitchen logo">
#title: "viniskitchen"
#description: "Homestyle Indian food and catering. Lady‑owned, community‑loved."
timezone: America/Los_Angeles
#theme: jekyll-theme-cayman
markdown: kramdown

author: "Vineetha Pai"
email: "reachus@vinniskitchen.com"
baseurl: "" 
url: "https://devsite.vinniskitchen.com"
# add after existing options
sass:
  style: compressed